### ISSUE TITLE
Documents Launches An Unresponsive White Window

### ISSUE THREAD

**Issue by Saroufim** [flathub/org.gnome.Documents#3]
After the last update, Documents launches a white window with a transparent header. The window is unresponsive and the application does nothing.

**Comment by nedrichards** [comment]
Which version of tracker do you have on your operating system? This flatpak uses the host tracker to find files and access metadata about them.

**Comment by Saroufim** [comment]
I'm running Fedora 27 with tracker-2.0.3-1. I really doubt the issue is with tracker. Perhaps a screenshot oughta give you a better idea:

![captura de pantalla de 2018-04-02 22-25-33](https://user-images.githubusercontent.com/4712288/38212107-47efd738-36c5-11e8-8cc5-fd366d35c80f.png)

**Comment by nedrichards** [comment]
@Saroufim interesting - the reason I asked is that your description matched an issue I'd previously seen. If you start it with `flatpak run` on the command line do you get any useful output?

**Comment by Saroufim** [comment]
With flatpak run org.gnome.Documents I get no information whatsoever. The
app launches and the terminal returns to command prompt.

**Comment by bochecha** [comment]
I just installed Documents from Flathub on Fedora 28, it works just fine. :confused:

**Comment by Saroufim** [comment]
Apparently this is a tracker issue. Almost all the apps that use tracker are corrupt somehow and I can't figure out why the metadata is corrupt. Journalctl spawns 10,000+ lines for tracker and that makes nearly impossible to find relevant info.

**Comment by jurf** [comment]
It used to work for me, now I get this:

![obrazok](https://user-images.githubusercontent.com/7472425/48288306-f4883180-e46b-11e8-9781-ecd89b0a686e.png)

**Comment by BrainBlasted** [comment]
I've put out a new release 3.30.1. Please try it and see if you can reproduce now.

**Comment by BrainBlasted** [comment]
@Exalm has confirmed that this is no longer an issue as of 3.30.1. Closing.
